version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tippspiel
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - /app/prisma
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
